### ISSUE TITLE
samsung-a5: display does not work in U-Boot when regulators are active

### ISSUE THREAD

**Issue by samcday** [msm8916-mainline/gen-uboot-img#1]
The panel in my Samsung A5 goes blank when booting into U-Boot. As suggested by @TravMurav, it can be worked around by removing both regulators on the panel:

<details><summary>msm8916-samsung-a5u-eur.dts remove regulators patch</summary>

```
diff --git a/arch/arm64/boot/dts/qcom/msm8916-samsung-a5u-eur.dts b/arch/arm64/boot/dts/qcom/msm8916-samsung-a5u-eur.dts
index 6f22afd40fa6..d40d7d624d6e 100644
--- a/arch/arm64/boot/dts/qcom/msm8916-samsung-a5u-eur.dts
+++ b/arch/arm64/boot/dts/qcom/msm8916-samsung-a5u-eur.dts
@@ -9,29 +9,6 @@ / {
 	compatible = "samsung,a5u-eur", "qcom,msm8916";
 	chassis-type = "handset";
 
-	reg_vlcd_vdd3: regulator-vlcd-vdd3 {
-		compatible = "regulator-fixed";
-		regulator-name = "vlcd_vdd3";
-		regulator-min-microvolt = <1800000>;
-		regulator-max-microvolt = <1800000>;
-		vin-supply = <&pm8916_s4>;
-
-		gpio = <&tlmm 87 GPIO_ACTIVE_HIGH>;
-		enable-active-high;
-
-		pinctrl-names = "default";
-		pinctrl-0 = <&lcd_on_default>;
-	};
-
-	reg_vlcd_vci: regulator-vlcd-vci {
-		compatible = "regulator-fixed";
-		regulator-name = "vlcd_vci";
-		regulator-min-microvolt = <3000000>;
-		regulator-max-microvolt = <3000000>;
-
-		gpio = <&tlmm 87 GPIO_ACTIVE_HIGH>;
-		enable-active-high;
-	};
 
 	reg_touch_key: regulator-touch-key {
 		compatible = "regulator-fixed";
@@ -89,8 +66,6 @@ panel@0 {
 		compatible = "samsung,ea8061v-ams497ee01";
 		reg = <0>;
 
-		vdd3-supply = <&reg_vlcd_vdd3>;
-		vci-supply = <&reg_vlcd_vci>;
 		reset-gpios = <&tlmm 25 GPIO_ACTIVE_LOW>;
 
 		port {
```

</details> 

I confirmed that *both* regulators must be removed. Removing one or the other continues to display a blank screen.

**Comment by TravMurav** [comment]
Quick look into u-boot sources suggests that it's possibly this (unsure if this is compiled in for the generic target):

https://elixir.bootlin.com/u-boot/v2024.07-rc1/source/arch/arm/mach-snapdragon/board.c#L165

This seems to disable all regulators but ones marked as boot-on. You could try adding `regulator-boot-on;` to both regulators and see if this fixes it.

**Comment by samcday** [comment]
> Quick look into u-boot sources suggests that it's possibly this (unsure if this is compiled in for the generic target):

Nice catch!

That was indeed the issue. Adding `regulator-boot-on;` to the regulators fixes the issue. I now have a working screen in U-Boot and the regulators show in `dm tree`:

```
 regulator     2  [ + ]   regulator_fixed       |-- regulator-vlcd-vdd3
 regulator     3  [   ]   regulator_fixed       |-- regulator-vlcd-vci
 regulator     4  [ + ]   regulator_fixed       |-- regulator-touch-key
 video         0  [ + ]   simple_video          |-- framebuffer@8e000000
 vidconsole    0  [ + ]   vidconsole0           |   `-- framebuffer@8e000000.vidconso
```

Should we apply this fix via DT fixups in lk2nd?

**Comment by TravMurav** [comment]
No. Could you please make a `--squash` commit against whichever adds those regulator nodes in msm8916-mainline/linux with following content:

```
[Sam: Add regulator-boot-on to preserve display in u-boot]
Signed-off-by: name <email>
```

and make a PR against wip/msm8916/6.9-rc6. Then I will squash it in since it's a reasonable thing to carry and upstream

**Comment by samcday** [comment]
:+1: Done: https://github.com/msm8916-mainline/linux/pull/355

Closing this out since the issue is fixed for this device, at least. I do wonder how many more devices will need a similar change.
