### ISSUE TITLE
flashing thirdstage.ext2 doesnt work

### ISSUE THREAD

**Issue by Lordalt** [msm8916-mainline/gen-uboot-img#5]
it just spews out this error: "remote: image is not a boot image" when i try to flash it

**Comment by TravMurav** [comment]
You might want to update to more recent lk2nd. Unfortunately the first experimental build I have in releases is quite outdated and has it's issues but I never got my hands to updating things sadly

**Comment by Lordalt** [comment]
so i should just update lk2nd?

**Comment by TravMurav** [comment]
Yes, I've made a mistake at some point and with lk2nd built in this repo you can't actually flash the ext2 boot image to boot partition. I've removed that check for lk2nd shortly after but never had time to update this repo. FWIW by this moment I think we could use fully mainline u-boot as well but this would need to be re-validated too

**Comment by Lordalt** [comment]
ok so yes updating fixed this. this issue is free to be closed.
